// examples/sdk-demos/frontend/react-vite/src/App.jsx
import { useState } from 'react';

import * as MonitorSdk from 'error-monitor-sdk';
import * as ReactMonitor from 'error-monitor-sdk/integrations/react';

const { MonitorErrorBoundary } = ReactMonitor;

function Bomb() {
  const [blow, setBlow] = useState(false);
  if (blow) {
    throw new Error('React demo: ошибка внутри MonitorErrorBoundary');
  }
  return (
    <button type="button" onClick={() => setBlow(true)}>
      Ошибка в Boundary → /track
    </button>
  );
}

export default function App() {
  return (
    <div style={{ fontFamily: 'system-ui', padding: '1rem', maxWidth: '32rem' }}>
      <h1 style={{ fontSize: '1.25rem' }}>Error Monitor — React + Vite</h1>
      <p style={{ color: '#555', fontSize: '0.9rem' }}>
        Убедитесь, что коллектор запущен, CORS разрешён для этого origin, в <code>.env</code> заданы{' '}
        <code>VITE_*</code>.
      </p>
      <ul style={{ lineHeight: 1.8 }}>
        <li>
          <MonitorErrorBoundary
            fallback={(err) => (
              <span style={{ color: '#b91c1c' }}>Поймано в UI: {err.message} (событие ушло в коллектор)</span>
            )}
          >
            <Bomb />
          </MonitorErrorBoundary>
        </li>
        <li>
          <button
            type="button"
            onClick={() =>
              MonitorSdk.trackEvent('react_demo_manual', { source: 'vite-demo' }, window.location.href)
            }
          >
            Отправить track_event
          </button>
        </li>
        <li>
          <button
            type="button"
            onClick={() => {
              setTimeout(() => {
                throw new Error('React demo: глобальная ошибка (window.onerror / browser.js)');
              }, 0);
            }}
          >
            Глобальная ошибка (через setTimeout)
          </button>
        </li>
      </ul>
    </div>
  );
}

// examples/sdk-demos/frontend/vue-vite/src/App.vue
<script setup>
import * as MonitorSdk from 'error-monitor-sdk';

function boom() {
  throw new Error('Vue 3 demo: ошибка через app.config.errorHandler');
}

function track() {
  MonitorSdk.trackEvent('vue_demo_manual', { source: 'vite-demo' }, window.location.href);
}

function globalErr() {
  setTimeout(() => {
    throw new Error('Vue demo: глобальная ошибка (browser.js)');
  }, 0);
}
</script>

<template>
  <div style="font-family: system-ui; padding: 1rem; max-width: 32rem">
    <h1 style="font-size: 1.25rem">Error Monitor — Vue 3 + Vite</h1>
    <p style="color: #555; font-size: 0.9rem">
      CORS на коллекторе, <code>.env</code> с префиксом <code>VITE_</code>.
    </p>
    <ul style="line-height: 2">
      <li><button type="button" @click="boom">Ошибка рендера → errorHandler → /track</button></li>
      <li><button type="button" @click="track">Отправить track_event</button></li>
      <li><button type="button" @click="globalErr">Глобальная ошибка (setTimeout)</button></li>
    </ul>
  </div>
</template>
